../compiler/kompilator 0-div-mod.imp 0-div-mod.mr
../compiler/kompilator 00-div-mod.imp 00-div-mod.mr
../compiler/kompilator 1-numbers.imp 1-numbers.mr
../compiler/kompilator 2-fib.imp 2-fib.mr
../compiler/kompilator 3-fib-factorial.imp 3-fib-factorial.mr
../compiler/kompilator 4-factorial.imp 4-factorial.mr
../compiler/kompilator 5-tab.imp 5-tab.mr
../compiler/kompilator 6-mod-mult.imp 6-mod-mult.mr
../compiler/kompilator 7-loopiii.imp 7-loopiii.mr
../compiler/kompilator 8-for.imp 8-for.mr
../compiler/kompilator 9-sort.imp 9-sort.mr
../compiler/kompilator program0.imp program0.mr
../compiler/kompilator program1.imp program1.mr
../compiler/kompilator program2.imp program2.mr
